MODEL:
    NUM_CLASSES: 11
    THRESHOLD: 0.75
    PRIORS:
        MIN_SIZES: [[15, 15], [30, 30], [80, 80], [162, 162], [213, 213], [264, 264]]
        MAX_SIZES: [[30, 30], [50, 50], [130, 130], [213, 213], [264, 264], [315, 315]]
        
        # Original
        #MIN_SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
        #MAX_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
    BACKBONE:
        NAME: 'medium'
        PRETRAINED: False
        OUT_CHANNELS: [128, 256, 256, 128, 64, 64]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [300, 300]

DATASETS:
    TRAIN: ("mnist_detection_train", "mnist_detection_val")
    TEST: ("mnist_detection_val", )
SOLVER:
    MAX_ITER: 15000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1.2e-3
    WEIGHT_DECAY: 3e-4

OUTPUT_DIR: 'outputs/medium'
DATASET_DIR: "datasets"